### ISSUE TITLE
why the runnermode is spawn zombieteammate

### ISSUE THREAD

**Issue by MsLGXC** [zeThijs/SM-NMRiH-diffmoder_fork#1]
if spawn zombieteammate,u cant do most mission,if the map mission requirement u to kill all zombie.
because map not count zombieteammate kills
how to fix it to nomarl runner not zombieteammate?

**Comment by zeThijs** [comment]
Huhm github did not notify of your issue, my apologies.
It's true the runners spawned by the plugin generall arent counted by map logic and break the map in certain situations. 

Perhaps the mothballed fix could be re-enabled again. This uses Vscript's BecomeRunner() method. However, people have voiced discontent with the increase in difficulty with this method. This is due to in some maps, this results in an impossibly large stream of continuous runners. It's worth revisiting how true this is.

**Comment by MsLGXC** [comment]
Last year, I requested Dysphie's help and he provided me with the allrunner plugin he had written and used for several years, which worked very well

**Comment by MsLGXC** [comment]
In addition, you mentioned infinitely generated zombies. Yes, the principle of this plugin seems to be to delete existing zombies and generate an equal number of runners. This will cause problems with most maps that require kill counts and have special monsters

**Comment by MsLGXC** [comment]
can change servercfg sv_spawn_regen_target 0 
then server will not respawn deadzombie

**Comment by MsLGXC** [comment]
If only the allrunner mode is needed, there are currently better plugins in GitHub to replace it.
Multi mode is still good, if these issues are fixed
But I prefer to play full run and spend most of my time playing infallrunner mode

**Comment by zeThijs** [comment]
True Dysphie's allrunner plugin is probably better if you prefer allrunner all the time anyway lol
